# Generated by Django 3.1.4 on 2020-12-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('num_of_responses', models.IntegerField()),
            ],
        ),
    ]
